name: Generate ASCII Artwork
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: List repo files
          run: ls -ltra
          
        - name: Executing Shell Script
          run: ./ascii_script.sh
